Repository yamada-ui/yamada-components, pull requests merged in 2024-08, with the labels that each got.

#394 Updated payload structure in workflow
  .github/workflows/observe-issue-and-pull-request.yml
Labels: merge request

#393 Updated curl payload in GitHub workflow
  .github/workflows/observe-issue-and-pull-request.yml
Labels: review wanted, merge request

#386 refactor(component): exclude empty categories from page
  utils/component.ts
  utils/next.ts
Labels: merge request

#399 Component preview is not working properly
  utils/component.ts
Labels: merge request

#398 refactor: breakpoints-layouts-grids
  contents/layouts/grids/asymmetrical-columns/index.tsx
  contents/layouts/grids/leading-item/index.tsx
Labels: merge request

#402 refactor(footer): update footer layouts
  contents/layouts/footers/footer-centerd/index.tsx
  contents/layouts/footers/footer-links/index.tsx
  contents/layouts/footers/footer-simple/index.tsx
  contents/layouts/footers/footer-social-icons/index.tsx
Labels: merge request

#408 fix: changed `size` to `boxSize`
  components/data-display/component-preview.tsx
Labels: review wanted

#420 Update dependencies and remove glob
  package.json
  pnpm-lock.yaml
Labels: merge request

#423 refactor(tab-order): changed `fileList` to be `files.order`
  @types/component.d.ts
  contents/navigation/steppers/simple-stepper/metadata.json
  contents/overlay/dialogs/gdpr-cookie-dialog/metadata.json
  utils/component.ts
Labels: merge request

#416 fix(footer): fixed the `footer-centered` directory typo
  contents/layouts/footers/footer-centered/index.tsx
  contents/layouts/footers/footer-centered/metadata.json
Labels: merge request

#411 Update labels and descriptions
  .github/ISSUE_TEMPLATE/bug_report.ja.yml
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/feature_request.ja.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
Labels: review wanted, merge request

#424 Update ComponentPreview props and layout
  components/data-display/component-preview.tsx
  components/layouts/component-body.tsx
Labels: merge request

#404 feat(avatar): added animated `avatar` examples
  contents/data-display/avatars/avatar-with-text/index.tsx
  contents/data-display/avatars/avatars-with-hover-motion/index.tsx
  contents/data-display/avatars/avatars-with-hover-motion/metadata.json
  contents/data-display/avatars/avatars-with-hover-motion/users.ts
  contents/data-display/avatars/avatars-with-hover/index.tsx
  contents/data-display/avatars/avatars-with-hover/metadata.json
  contents/data-display/avatars/avatars-with-hover/users.ts
Labels: review wanted, merge request

#412 feat(hero): add `hero` component examples
  contents/page-sections/hero-headers/metadata.json
  contents/page-sections/hero-headers/with-background-image/index.tsx
  contents/page-sections/hero-headers/with-background-image/metadata.json
  contents/page-sections/hero-headers/with-bullets/hero.svg
  contents/page-sections/hero-headers/with-bullets/index.tsx
  contents/page-sections/hero-headers/with-bullets/metadata.json
  contents/page-sections/hero-headers/with-content-on-left/index.tsx
  contents/page-sections/hero-headers/with-content-on-left/metadata.json
Labels: merge request

#400 refactor: breakpoints-page-sections/faq
  contents/page-sections/faq/with-image/index.tsx
Labels: merge request

#406 Add `LineChart` examples
  contents/data-display/charts/metadata.json
  contents/data-display/charts/weekly-temperature-chart/index.tsx
  contents/data-display/charts/weekly-temperature-chart/metadata.json
Labels: review wanted, merge request

#421 Update lefthook config for prettier and eslint
  lefthook.yaml
Labels: review wanted, merge request

#396 Fix container query in banners
  contents/data-display/banners/cookie/index.tsx
Labels: merge request

#430 Updated commit message
  .github/workflows/sync.yml
Labels: merge request

#426 refactor(drawer): improved drawer visual design and code
  contents/overlay/drawers/form-drawer/index.tsx
  contents/overlay/drawers/navigation-drawer/data.ts
  contents/overlay/drawers/navigation-drawer/index.tsx
Labels: merge request

#413 feat(contact-us): added `contact us` page section examples
  contents/page-sections/contact-us/form/contacts.ts
  contents/page-sections/contact-us/form/index.tsx
  contents/page-sections/contact-us/form/metadata.json
  contents/page-sections/contact-us/metadata.json
  contents/page-sections/contact-us/touch-form/contacts.ts
  contents/page-sections/contact-us/touch-form/index.tsx
  contents/page-sections/contact-us/touch-form/metadata.json
Labels: review wanted, merge request

#428 refactor(chart): improved `chart` range selector and style
  contents/data-display/charts/weekly-temperature-chart/index.tsx
  contents/data-display/charts/weekly-temperature-chart/locations.ts
  contents/data-display/charts/weekly-temperature-chart/metadata.json
  contents/data-display/charts/weekly-temperature-chart/utils.ts
Labels: merge request

#431 added simple charts
  contents/data-display/charts/simple-charts/index.tsx
  contents/data-display/charts/simple-charts/metadata.json
Labels: review wanted, merge request

#432 added `BarChart` with label example
  contents/data-display/charts/bar-chart-label/index.tsx
  contents/data-display/charts/bar-chart-label/metadata.json
Labels: merge request

#433 refactor(metadata): improved files order logic
  contents/navigation/steppers/simple-stepper/metadata.json
  contents/overlay/dialogs/gdpr-cookie-dialog/metadata.json
  utils/component.ts
Labels: review wanted, merge request

#437 Fix code preview border top
  components/data-display/component-code-preview.tsx
  components/layouts/component-body.tsx
Labels: review wanted, merge request

#439 Updated token in sync workflow
  .github/workflows/sync.yml
Labels: merge request

#442 Rename `TemperatureCharts`
  contents/data-display/charts/date-range-temperature-chart/index.tsx
  contents/data-display/charts/date-range-temperature-chart/locations.ts
  contents/data-display/charts/date-range-temperature-chart/metadata.json
  contents/data-display/charts/date-range-temperature-chart/utils.ts
  contents/data-display/charts/weekly-temperature-chart/metadata.json
Labels: merge request

#441 Refactoring of temperature chart
  contents/data-display/charts/bar-chart-label/metadata.json
  contents/data-display/charts/date-range-temperature-chart/index.tsx
  contents/data-display/charts/date-range-temperature-chart/locations.ts
  contents/data-display/charts/date-range-temperature-chart/metadata.json
  contents/data-display/charts/simple-charts/metadata.json
  contents/data-display/charts/temperature-chart/custom-radio.tsx
  contents/data-display/charts/temperature-chart/index.tsx
  contents/data-display/charts/temperature-chart/metadata.json
  contents/data-display/charts/temperature-chart/utils.ts
Labels: review wanted, merge request

#445 Add `DonutActive` example
  contents/data-display/charts/donut-active/index.tsx
  contents/data-display/charts/donut-active/metadata.json
  package.json
  pnpm-lock.yaml
Labels: review wanted, merge request
