Repository yamada-ui/yamada-components, pull requests merged in 2024-09, with the labels that each got.

#454 Updated MixedArray type definition
  utils/array.ts
Labels: merge request

#451 refactor of temperature chart
  contents/data-display/charts/temperature-chart/index.tsx
  contents/data-display/charts/temperature-chart/utils.ts
Labels: review wanted, merge request

#449 feat: added Chart with Text example
  contents/data-display/charts/chart-with-text/index.tsx
  contents/data-display/charts/chart-with-text/metadata.json
  contents/layouts/headers/double-header/index.tsx
  contents/layouts/headers/with-tabs/index.tsx
  package.json
  pnpm-lock.yaml
Labels: merge request

#453 Added font tokens for styling
  theme/tokens/fonts.ts
  theme/tokens/index.ts
Labels: review wanted, merge request

#457 feat(dynamic-islands): added `dynamic-island` component examples
  contents/overlay/dynamic-islands/dynamic-island/index.tsx
  contents/overlay/dynamic-islands/dynamic-island/metadata.json
  contents/overlay/dynamic-islands/metadata.json
  contents/overlay/dynamic-islands/music-dynamic-island/index.tsx
  contents/overlay/dynamic-islands/music-dynamic-island/metadata.json
  contents/overlay/dynamic-islands/phone-call-dynamic-island/index.tsx
  contents/overlay/dynamic-islands/phone-call-dynamic-island/metadata.json
  contents/overlay/dynamic-islands/simple-dynamic-island/index.tsx
  contents/overlay/dynamic-islands/simple-dynamic-island/metadata.json
  contents/overlay/dynamic-islands/springy-dynamic-island/index.tsx
  contents/overlay/dynamic-islands/springy-dynamic-island/metadata.json
Labels: review wanted, merge request

#473 refactor(comments): updated `comments` styles
  contents/data-display/comments/comment/index.tsx
  contents/data-display/comments/with-html-content/index.tsx
Labels: merge request

#476 refactor(texts): updated `texts` styles
  contents/typography/texts/on-scroll/index.tsx
Labels: merge request

#452 feat(timeline): added `timeline` component examples
  contents/data-display/timeline/animated-timeline/calendar-icon.tsx
  contents/data-display/timeline/animated-timeline/index.tsx
  contents/data-display/timeline/animated-timeline/metadata.json
  contents/data-display/timeline/animated-timeline/timeline-item.tsx
  contents/data-display/timeline/animated-timeline/timeline.ts
  contents/data-display/timeline/animated-timeline/utils.ts
  contents/data-display/timeline/custom-icon/calendar-icon.tsx
  contents/data-display/timeline/custom-icon/index.tsx
  contents/data-display/timeline/custom-icon/metadata.json
  contents/data-display/timeline/custom-icon/timeline-item.tsx
  contents/data-display/timeline/custom-icon/timeline.ts
  contents/data-display/timeline/metadata.json
  contents/data-display/timeline/middle-line/calendar-icon.tsx
  contents/data-display/timeline/middle-line/index.tsx
  contents/data-display/timeline/middle-line/metadata.json
  contents/data-display/timeline/middle-line/timeline-item.tsx
  contents/data-display/timeline/middle-line/timeline.ts
  contents/data-display/timeline/middle-line/utils.ts
  contents/data-display/timeline/simple-timeline/index.tsx
  contents/data-display/timeline/simple-timeline/metadata.json
  contents/data-display/timeline/simple-timeline/timeline-item.tsx
  contents/data-display/timeline/simple-timeline/timeline.ts
Labels: merge request

#477 refactor(dividers): deleted unnecessary component examples
  contents/layouts/dividers/label-on-left/index.tsx
  contents/layouts/dividers/label-on-left/metadata.json
  contents/layouts/dividers/with-icon/index.tsx
  contents/layouts/dividers/with-icon/metadata.json
  contents/layouts/dividers/with-title-and-button/index.tsx
  contents/layouts/dividers/with-title-and-button/metadata.json
  contents/layouts/dividers/with-title-on-left/index.tsx
  contents/layouts/dividers/with-title-on-left/metadata.json
  contents/layouts/dividers/with-title/index.tsx
  contents/layouts/dividers/with-title/metadata.json
Labels: merge request

#478 refactor(footers): updated `footer` styles
  contents/layouts/footers/footer-centered/index.tsx
  contents/layouts/footers/footer-links/index.tsx
  contents/layouts/footers/footer-simple/index.tsx
Labels: merge request

#461 Remove unwanted components
  contents/data-display/tags/card-with-tags/index.tsx
  contents/data-display/tags/card-with-tags/metadata.json
  contents/data-display/tags/metadata.json
  contents/data-display/tags/reorder-tags/index.tsx
  contents/data-display/tags/reorder-tags/metadata.json
  contents/disclosure/metadata.json
  contents/disclosure/tabs/metadata.json
  contents/disclosure/tabs/with-badges/index.tsx
  contents/disclosure/tabs/with-badges/metadata.json
  contents/disclosure/tabs/with-icons/index.tsx
  contents/disclosure/tabs/with-icons/metadata.json
  contents/overlay/drawers/form-drawer/index.tsx
  contents/overlay/drawers/form-drawer/metadata.json
  contents/overlay/drawers/metadata.json
  contents/overlay/drawers/navigation-drawer/data.ts
  contents/overlay/drawers/navigation-drawer/index.tsx
  contents/overlay/drawers/navigation-drawer/metadata.json
  pages/disclosure/[[...slug]].page.tsx
Labels: merge request

#448 Add Empty States - Simple
  contents/feedback/empty-status/metadata.json
  contents/feedback/empty-status/simple/credit-card-icon.tsx
  contents/feedback/empty-status/simple/index.tsx
  contents/feedback/empty-status/simple/metadata.json
  package.json
  pnpm-lock.yaml
Labels: review wanted, merge request

#484 refactor(dialogs): updated `dialog` styles
  contents/overlay/dialogs/cookie-dialog/index.tsx
  contents/overlay/dialogs/gdpr-cookie-dialog/category-item.tsx
  contents/overlay/dialogs/gdpr-cookie-dialog/data.ts
  contents/overlay/dialogs/gdpr-cookie-dialog/index.tsx
  contents/overlay/dialogs/gdpr-cookie-dialog/metadata.json
  contents/overlay/dialogs/input-dialog/index.tsx
  contents/overlay/dialogs/simple-dialog/index.tsx
  contents/overlay/dialogs/three-buttons-dialog/index.tsx
Labels: review wanted

#486 Refactor `Headers` components
  contents/layouts/headers/double-header/index.tsx
  contents/layouts/headers/simple-header/index.tsx
  contents/layouts/headers/with-tabs/index.tsx
  contents/layouts/headers/with-tabs/metadata.json
  contents/layouts/headers/with-tabs/theme.ts
Labels: review wanted, merge request

#488 refactor(order): updated the file tab order logic
  @types/component.d.ts
  contents/data-display/charts/bar-chart-label/metadata.json
  contents/data-display/charts/chart-with-text/metadata.json
  contents/data-display/charts/donut-active/metadata.json
  contents/data-display/charts/metadata.json
  contents/data-display/charts/simple-charts/metadata.json
  contents/data-display/charts/temperature-chart/metadata.json
  contents/data-display/metadata.json
  contents/data-display/timeline/animated-timeline/metadata.json
  contents/data-display/timeline/custom-icon/metadata.json
  contents/data-display/timeline/metadata.json
  contents/data-display/timeline/middle-line/metadata.json
  contents/data-display/timeline/simple-timeline/metadata.json
  contents/feedback/metadata.json
  contents/forms/metadata.json
  contents/layouts/dividers/metadata.json
  contents/layouts/dividers/with-toolbar/index.tsx
  contents/layouts/footers/footer-simple/metadata.json
  contents/layouts/footers/footer-social-icons/metadata.json
  contents/layouts/footers/metadata.json
  contents/layouts/headers/metadata.json
  contents/layouts/headers/simple-header/metadata.json
  contents/layouts/metadata.json
  contents/metadata.json
  contents/navigation/metadata.json
  contents/navigation/navbars/double-navbar/metadata.json
  contents/navigation/navbars/metadata.json
  contents/navigation/navbars/navbar-with-tooltips/metadata.json
  contents/navigation/navbars/simple-navbar/metadata.json
  contents/navigation/navbars/with-segmented-control/metadata.json
  contents/overlay/dialogs/cookie-dialog/metadata.json
  contents/overlay/dialogs/gdpr-cookie-dialog/metadata.json
  contents/overlay/dialogs/input-dialog/metadata.json
  contents/overlay/dialogs/metadata.json
  contents/overlay/dialogs/simple-dialog/metadata.json
  contents/overlay/dialogs/three-buttons-dialog/metadata.json
  contents/overlay/dynamic-islands/dynamic-island/metadata.json
  contents/overlay/dynamic-islands/metadata.json
  contents/overlay/dynamic-islands/music-dynamic-island/metadata.json
  contents/overlay/dynamic-islands/phone-call-dynamic-island/metadata.json
  contents/overlay/dynamic-islands/simple-dynamic-island/metadata.json
  contents/overlay/dynamic-islands/springy-dynamic-island/metadata.json
  contents/overlay/menus/menu-with-icon/metadata.json
  contents/overlay/menus/metadata.json
  contents/overlay/menus/simple-with-descriptions/metadata.json
  contents/overlay/metadata.json
  contents/page-sections/hero-headers/metadata.json
  contents/page-sections/hero-headers/with-background-image/metadata.json
  contents/page-sections/hero-headers/with-bullets/metadata.json
  contents/page-sections/metadata.json
  contents/typography/metadata.json
  pages/search/index.page.tsx
  utils/component.ts
  utils/next.ts
Labels: review wanted, merge request

#472 refactor(avatars): updated `avatars` styles
  contents/data-display/avatars/avatar-with-text/index.tsx
  contents/data-display/avatars/avatars-with-hover-motion/index.tsx
  contents/data-display/avatars/avatars-with-hover/index.tsx
Labels: merge request

#479 refactor(dropzones): updated `dropzone` styles
  contents/forms/dropzones/with-button/index.tsx
  contents/forms/dropzones/with-image-preview/index.tsx
Labels: review wanted, merge request

#494 Specify maxW for barchart
  contents/data-display/charts/bar-chart-label/index.tsx
Labels: merge request

#496 Refactor `Navbar` component examples
  contents/navigation/navbars/double-navbar/index.tsx
  contents/navigation/navbars/navbar-with-tooltips/index.tsx
  contents/navigation/navbars/simple-navbar/index.tsx
  contents/navigation/navbars/with-segmented-control/index.tsx
Labels: merge request

#498 fix(fontSize): modified icon size to fontSize
  contents/feedback/progress/quest-progress/index.tsx
  contents/navigation/navbars/double-navbar/index.tsx
  contents/overlay/menus/menu-with-icon/index.tsx
Labels: merge request

#499 Add `ignore` process
  @types/component.d.ts
  utils/component.ts
Labels: merge request

#501 fix: change fontWeight in `Text`
  contents/typography/texts/on-scroll/index.tsx
Labels: merge request

#502 Added header with search box
  contents/layouts/headers/metadata.json
  contents/layouts/headers/with-search/index.tsx
  contents/layouts/headers/with-search/metadata.json
Labels: merge request

#481 refactor(page-sections): updated `page-sections` styles
  contents/page-sections/authentication/authentication-form/index.tsx
  contents/page-sections/authentication/forgot-password/index.tsx
  contents/page-sections/contact-us/form/index.tsx
  contents/page-sections/contact-us/touch-form/index.tsx
  contents/page-sections/error-pages/404-page/index.tsx
  contents/page-sections/error-pages/500-page/index.tsx
  contents/page-sections/error-pages/with-image/index.tsx
Labels: merge request

#504 Updated dependencies versions
  package.json
  pnpm-lock.yaml
Labels: merge request

#480 refactor(dynamic-islands): updated `dynamic island` styles
  contents/overlay/dynamic-islands/dynamic-island/index.tsx
  contents/overlay/dynamic-islands/dynamic-island/metadata.json
  contents/overlay/dynamic-islands/music-dynamic-island/index.tsx
  contents/overlay/dynamic-islands/music-dynamic-island/metadata.json
  contents/overlay/dynamic-islands/phone-call-dynamic-island/index.tsx
  contents/overlay/dynamic-islands/phone-call-dynamic-island/metadata.json
  contents/overlay/dynamic-islands/simple-dynamic-island/index.tsx
  contents/overlay/dynamic-islands/simple-dynamic-island/metadata.json
  contents/overlay/dynamic-islands/springy-dynamic-island/index.tsx
  contents/overlay/dynamic-islands/springy-dynamic-island/metadata.json
Labels: merge request

#508 fix(progress-bar): reduce whitespace and add rounded corners in Quest Progress Component
  contents/feedback/progress/quest-progress/index.tsx
Labels: merge request
